-- Antonio Bellanova Luxury - Initial Schema
-- Run with: npm run db:migrate

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  uid TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'USER',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS categories (
  id SERIAL PRIMARY KEY,
  name_de TEXT NOT NULL,
  name_en TEXT,
  slug TEXT NOT NULL UNIQUE,
  parent_id INTEGER,
  description_de TEXT,
  description_en TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS brands (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description_de TEXT,
  description_en TEXT,
  logo_url TEXT,
  status TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  sku TEXT,
  brand_id INTEGER,
  model TEXT,
  category_id INTEGER,
  type TEXT,
  condition TEXT,
  year TEXT,
  description_de TEXT,
  description_en TEXT,
  short_description_de TEXT,
  short_description_en TEXT,
  title_de TEXT,
  title_en TEXT,
  condition_de TEXT,
  condition_en TEXT,
  specifications_de TEXT,
  specifications_en TEXT,
  scope_of_delivery_de TEXT,
  scope_of_delivery_en TEXT,
  price NUMERIC(10,2) NOT NULL,
  currency TEXT DEFAULT 'EUR',
  status TEXT DEFAULT 'DRAFT',
  images JSONB,
  main_image TEXT,
  material TEXT,
  diameter TEXT,
  movement TEXT,
  box TEXT,
  papers TEXT,
  specifications JSONB,
  condition_group TEXT,
  source_condition TEXT,
  source_rank TEXT,
  case_rank TEXT,
  band_rank TEXT,
  overall_rank TEXT,
  condition_remarks TEXT,
  maintenance_performed TEXT,
  maintenance_description TEXT,
  daily_rate_seconds NUMERIC(10,2),
  daily_rate_display TEXT,
  source_url TEXT,
  source_provider TEXT,
  source_product_id TEXT,
  source_variant_id TEXT,
  source_data JSONB,
  purchase_price NUMERIC(10,2),
  purchase_price_original NUMERIC(10,2),
  purchase_price_eur NUMERIC(10,2),
  purchase_currency TEXT,
  exchange_rate NUMERIC(10,4),
  exchange_rate_source TEXT,
  exchange_rate_fetched_at TIMESTAMP,
  landed_cost NUMERIC(10,2),
  pricing_mode TEXT DEFAULT 'MARGIN',
  target_margin NUMERIC(5,2),
  target_margin_percent NUMERIC(5,2),
  calculated_net_selling_price NUMERIC(10,2),
  net_sale_price NUMERIC(10,2),
  tax_amount NUMERIC(10,2),
  calculated_gross_selling_price NUMERIC(10,2),
  gross_sale_price NUMERIC(10,2),
  manual_gross_selling_price NUMERIC(10,2),
  manual_gross_sale_price NUMERIC(10,2),
  actual_profit NUMERIC(10,2),
  profit_eur NUMERIC(10,2),
  actual_margin NUMERIC(5,2),
  effective_margin_percent NUMERIC(5,2),
  markup NUMERIC(5,2),
  import_vat NUMERIC(10,2),
  import_vat_eur NUMERIC(10,2),
  import_vat_type TEXT,
  is_input_tax_deductible TEXT DEFAULT 'true',
  international_shipping NUMERIC(10,2),
  customs_broker NUMERIC(10,2),
  customs_broker_fee NUMERIC(10,2),
  customs_clearance NUMERIC(10,2),
  customs_clearance_fee NUMERIC(10,2),
  handling_cost NUMERIC(10,2),
  other_capitalizable_costs NUMERIC(10,2),
  other_import_costs NUMERIC(10,2),
  customs_rate NUMERIC(5,2),
  customs_rate_percent NUMERIC(5,2),
  customs_amount NUMERIC(10,2),
  customs_amount_eur NUMERIC(10,2),
  manual_customs_amount_eur NUMERIC(10,2),
  margin NUMERIC(5,2),
  tax_type TEXT,
  tax_treatment TEXT,
  tax_rate_percent NUMERIC(5,2),
  shipping_cost NUMERIC(10,2),
  insurance_cost NUMERIC(10,2),
  authentication_cost NUMERIC(10,2),
  refurbishment_cost NUMERIC(10,2),
  hs_code TEXT,
  origin_country TEXT,
  dispatch_country TEXT,
  destination_country TEXT,
  seo_title_de TEXT,
  seo_description_de TEXT,
  seo_title_en TEXT,
  seo_description_en TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  published_at TIMESTAMP,
  published TEXT DEFAULT 'false',
  stock INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  order_number TEXT UNIQUE,
  user_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  payment_status TEXT DEFAULT 'PENDING',
  payment_method TEXT DEFAULT 'BANK_TRANSFER',
  total NUMERIC(10,2) NOT NULL,
  shipping_address JSONB,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS order_items (
  id SERIAL PRIMARY KEY,
  order_id INTEGER REFERENCES orders(id),
  product_id INTEGER REFERENCES products(id),
  product_name TEXT,
  product_image TEXT,
  quantity INTEGER NOT NULL,
  price NUMERIC(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS shop_settings (
  id SERIAL PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  value JSONB NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inquiries (
  id SERIAL PRIMARY KEY,
  type TEXT NOT NULL,
  status TEXT DEFAULT 'NEW',
  first_name TEXT,
  last_name TEXT,
  email TEXT NOT NULL,
  phone TEXT,
  subject TEXT,
  message TEXT,
  metadata JSONB,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wishlist_items (
  id SERIAL PRIMARY KEY,
  user_id TEXT NOT NULL,
  product_id INTEGER REFERENCES products(id),
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, product_id)
);
