/** Shared shop defaults — used by server and frontend fallback */
export const DEFAULT_SHOP_SETTINGS: Record<string, string> = {
  legalCompanyName: "Juwelen & Schmuckatelier Antonio Bellanova",
  shopBrandName: "Antonio Bellanova Luxury",
  shopName: "Juwelen & Schmuckatelier ANTONIO BELLANOVA",
  contactEmail: "antonio.bellanova@antoniobellanova.com",
  contactPhone: "+49 (0) 1637607805",
  contactAddress: "Ahornstraße 8\n50765 Köln, Deutschland",
  bankName: "Sparkasse KölnBonn",
  bankIban: "DE95370501981959185305",
  bankBic: "COLSDE33XXX",
  bankAccountHolder: "Antonio Bellanova",
  paymentInstructionsDe: "Bitte überweisen Sie den Betrag unter Angabe Ihrer Bestellnummer als Verwendungszweck.",
  paymentInstructionsEn: "Please transfer the amount using your order number as payment reference.",
  vatId: "",
  taxNumber: "",
  instagramUrl: "",
  facebookUrl: "",
  whatsappNumber: "491637607805",
  googleMapsUrl: "https://maps.google.com/?q=Ahornstraße+8+50765+Köln+Deutschland",
  authenticityNoteDe: "Jedes Stück wird von unseren Experten auf Echtheit geprüft. Auf Wunsch stellen wir ein Echtheitszertifikat aus.",
  authenticityNoteEn: "Every piece is inspected by our experts for authenticity. Certificates of authenticity are available on request.",
  marginTaxNoteDe: "Preise verstehen sich inkl. MwSt. Gebrauchtware nach §25a UStG (Differenzbesteuerung).",
  marginTaxNoteEn: "Prices include VAT. Pre-owned goods taxed under Section 25a UStG (margin scheme).",
  shippingCostDe: "0",
  shippingCostEu: "29",
  shippingCostWorld: "79",
  shippingFreeFrom: "500",
  priceOnRequestFrom: "10000",
  stripeFeePercent: "1.5",
  stripeFeeFixed: "0.25",
  premiumCardFeePercent: "2.8",
  premiumCardFeeFixed: "0.25",
  internationalCardFeePercent: "3.15",
  internationalCardFeeFixed: "0.25",
  stripeCurrency: "EUR",
  roundingStep: "10",
  roundingMode: "ROUND_UP",
  defaultPricingModel: "STANDARD",
  stripeEnabled: "true",
  bankTransferEnabled: "true",
  prepaymentEnabled: "true",
  paymentMethodsJson: JSON.stringify([
    {
      id: "STRIPE",
      enabled: true,
      name: "Karte (Stripe)",
      description: "Sichere Online-Zahlung per Kredit- oder Debitkarte",
      sortOrder: 1,
    },
    {
      id: "BANK_TRANSFER",
      enabled: true,
      name: "Banküberweisung",
      description: "Zahlung per Banküberweisung",
      sortOrder: 2,
    },
    {
      id: "PREPAYMENT",
      enabled: true,
      name: "Vorkasse",
      description: "Zahlung im Voraus per Überweisung",
      sortOrder: 3,
    },
  ]),
  shippingExpressCostDe: "49",
  shippingExpressCostEu: "79",
  shippingExpressCostWorld: "129",
  pickupNoteDe: "Abholung im Atelier Köln nach Terminvereinbarung — kostenlos.",
  pickupNoteEn: "Pick-up at our Cologne atelier by appointment — free of charge.",
  certificateNoteDe: "Echtheitszertifikat auf Anfrage erhältlich.",
  certificateNoteEn: "Certificate of authenticity available on request.",
  testimonial1De: "„Hervorragende Beratung und einwandfreie Abwicklung — die Uhr übertrifft die Erwartungen.“",
  testimonial1En: "“Excellent advice and seamless transaction — the watch exceeds expectations.”",
  testimonial1Author: "Privater Sammler, Köln",
};
